//  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class Problem2_Fibo {
    public static void main(String[] args) {
        System.out.println(sumFibo(0, 1, 2));
    }

    public static int sumFibo(int sum, int prev, int curr) {
        if (curr > 4000000) {
            return sum;
        }
        int newSum = sum;
        if (curr % 2 == 0) {
            newSum += curr;
        }
        return sumFibo(newSum, curr, prev + curr);
    }
}